# -*- coding: utf-8 -*-
"""mad libs game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hU4Ldp8ZuvDhvDhHjbLDLXt5FY1O8Rc-
"""



"""**Mad Libs Game In Python**"""

# user input
name = input("Enter the girl name: ")
programming_language = input("Enter a programming language: (eg: python, nextjs, typescript): ")
mentor = input("Enter the metor name: ")

#strory created
print("\n Here is my story base on mid libs game!")
print(f"once upon a time there was a girl named {name}.")
print(f"{name} was very intelligent and always learn new things")

print(f"{name} found a great metor name as {mentor} who was an expert in {programming_language}")
print(f"and also,her journey continues..!")